/**
 * Markdown 문서 렌더러
 */

import * as fs from 'fs';
import * as path from 'path';
import { ScreenSpec, InputField, ButtonSpec, GridColumn, EventSpec } from '../../config/types.js';

export class MarkdownRenderer {
  /**
   * 화면 명세서를 Markdown으로 렌더링
   */
  renderSpec(spec: ScreenSpec, screenshotPath?: string): string {
    const lines: string[] = [];

    // 제목
    const screenName = spec.header.screenName || spec.header.screenId;
    lines.push(`# ${screenName}`);
    lines.push('');
    lines.push(`> 화면 ID: \`${spec.header.screenId}\` | 버전: \`${spec.header.version}\``);
    lines.push('');

    // 문서 정보
    lines.push('## 문서 정보');
    lines.push('');
    lines.push(`| 항목 | 값 |`);
    lines.push(`|------|-----|`);
    lines.push(`| 작성일 | ${spec.header.createdAt} |`);
    lines.push(`| 작성자 | ${spec.header.createdBy} |`);
    if (spec.header.updatedAt) {
      lines.push(`| 수정일 | ${spec.header.updatedAt} |`);
      lines.push(`| 수정자 | ${spec.header.updatedBy || '-'} |`);
    }
    lines.push('');

    // 개요
    lines.push('## 1. 화면 개요');
    lines.push('');
    lines.push(`**설명:** ${spec.overview.description}`);
    lines.push('');

    if (spec.overview.accessPath) {
      lines.push(`**접근 경로:** ${spec.overview.accessPath}`);
      lines.push('');
    }

    if (spec.overview.businessRules) {
      lines.push(`**업무 규칙:** ${spec.overview.businessRules}`);
      lines.push('');
    }

    if (spec.overview.relatedScreens && spec.overview.relatedScreens.length > 0) {
      lines.push('### 관련 화면');
      lines.push('');
      for (const related of spec.overview.relatedScreens) {
        lines.push(`- \`${related.screenId}\`: ${related.screenName} (${related.relationship})`);
      }
      lines.push('');
    }

    // 스크린샷
    if (screenshotPath) {
      lines.push('## 2. 화면 레이아웃');
      lines.push('');
      const relativePath = screenshotPath.startsWith('/') ? screenshotPath : `./${screenshotPath}`;
      lines.push(`![${screenName}](${relativePath})`);
      lines.push('');
    }

    // 입력 항목
    if (spec.inputFields && spec.inputFields.length > 0) {
      lines.push('## 3. 입력 항목 정의');
      lines.push('');
      lines.push(this.renderInputFieldsTable(spec.inputFields));
      lines.push('');
    }

    // 버튼
    if (spec.buttons && spec.buttons.length > 0) {
      lines.push('## 4. 버튼/액션 정의');
      lines.push('');
      lines.push(this.renderButtonsTable(spec.buttons));
      lines.push('');
    }

    // 그리드 컬럼
    if (spec.gridColumns && spec.gridColumns.length > 0) {
      lines.push('## 5. 그리드 컬럼 정의');
      lines.push('');
      lines.push(this.renderGridColumnsTable(spec.gridColumns));
      lines.push('');
    }

    // 이벤트
    if (spec.events && spec.events.length > 0) {
      lines.push('## 6. 이벤트 처리');
      lines.push('');
      lines.push(this.renderEventsTable(spec.events));
      lines.push('');
    }

    // 메시지
    if (spec.messages && spec.messages.length > 0) {
      lines.push('## 7. 메시지 정의');
      lines.push('');
      lines.push(this.renderMessagesTable(spec.messages));
      lines.push('');
    }

    // 변경 이력
    if (spec.changeHistory && spec.changeHistory.length > 0) {
      lines.push('## 변경 이력');
      lines.push('');
      lines.push(this.renderChangeHistoryTable(spec.changeHistory));
      lines.push('');
    }

    // 푸터
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by KonaI Pipeline at ${new Date().toISOString()}*`);

    return lines.join('\n');
  }

  /**
   * 입력 항목 테이블
   */
  private renderInputFieldsTable(fields: InputField[]): string {
    const lines: string[] = [];
    lines.push('| 필드명 | 필드ID | 타입 | 길이 | 필수 | 설명 |');
    lines.push('|--------|--------|------|------|------|------|');

    for (const field of fields) {
      const required = field.required ? '**Y**' : 'N';
      lines.push(
        `| ${field.fieldName} | \`${field.fieldId || '-'}\` | ${field.dataType} | ${field.length || '-'} | ${required} | ${field.remarks || '-'} |`
      );
    }

    return lines.join('\n');
  }

  /**
   * 버튼 테이블
   */
  private renderButtonsTable(buttons: ButtonSpec[]): string {
    const lines: string[] = [];
    lines.push('| 버튼명 | ID | 이벤트 | 처리 내용 | API |');
    lines.push('|--------|-----|--------|----------|-----|');

    for (const button of buttons) {
      const api = button.apiEndpoint
        ? `\`${button.httpMethod || 'POST'} ${button.apiEndpoint}\``
        : '-';
      lines.push(
        `| ${button.buttonName} | \`${button.buttonId || '-'}\` | ${button.eventType} | ${button.action} | ${api} |`
      );
    }

    return lines.join('\n');
  }

  /**
   * 그리드 컬럼 테이블
   */
  private renderGridColumnsTable(columns: GridColumn[]): string {
    const lines: string[] = [];
    lines.push('| 컬럼명 | ID | 타입 | 너비 | 정렬 | 정렬가능 | 비고 |');
    lines.push('|--------|-----|------|------|------|---------|------|');

    for (const col of columns) {
      lines.push(
        `| ${col.columnName} | \`${col.columnId || '-'}\` | ${col.dataType} | ${col.width || 'auto'} | ${col.align} | ${col.sortable !== false ? 'Y' : 'N'} | ${col.remarks} |`
      );
    }

    return lines.join('\n');
  }

  /**
   * 이벤트 테이블
   */
  private renderEventsTable(events: EventSpec[]): string {
    const lines: string[] = [];
    lines.push('| 이벤트명 | ID | 트리거 | 대상 | 처리 내용 |');
    lines.push('|---------|-----|--------|------|----------|');

    for (const event of events) {
      lines.push(
        `| ${event.eventName} | \`${event.eventId}\` | ${event.triggerType} | ${event.targetId || '-'} | ${event.handler} |`
      );
    }

    return lines.join('\n');
  }

  /**
   * 메시지 테이블
   */
  private renderMessagesTable(
    messages: Array<{
      messageId: string;
      messageType: string;
      messageText: string;
      useCase?: string;
    }>
  ): string {
    const lines: string[] = [];
    lines.push('| 메시지ID | 유형 | 내용 | 사용 시점 |');
    lines.push('|---------|------|------|----------|');

    for (const msg of messages) {
      const typeEmoji = this.getMessageTypeEmoji(msg.messageType);
      lines.push(
        `| \`${msg.messageId}\` | ${typeEmoji} ${msg.messageType} | ${msg.messageText} | ${msg.useCase || '-'} |`
      );
    }

    return lines.join('\n');
  }

  /**
   * 변경 이력 테이블
   */
  private renderChangeHistoryTable(
    history: Array<{
      version: string;
      changedAt: string;
      changedBy: string;
      changeType: string;
      description: string;
    }>
  ): string {
    const lines: string[] = [];
    lines.push('| 버전 | 변경일 | 변경자 | 유형 | 내용 |');
    lines.push('|------|--------|--------|------|------|');

    for (const entry of history) {
      lines.push(
        `| ${entry.version} | ${entry.changedAt} | ${entry.changedBy} | ${entry.changeType} | ${entry.description} |`
      );
    }

    return lines.join('\n');
  }

  /**
   * 메시지 유형별 이모지
   */
  private getMessageTypeEmoji(type: string): string {
    const emojis: Record<string, string> = {
      info: 'ℹ️',
      success: '✅',
      warning: '⚠️',
      error: '❌',
      confirm: '❓',
    };
    return emojis[type] || '📝';
  }

  /**
   * 파일로 저장
   */
  saveToFile(content: string, outputPath: string): void {
    const dir = path.dirname(outputPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content, 'utf-8');
  }
}
