export interface AgentChatSession {
  id: string;
  title: string;
  date: string;
  time: string;
  messageCount: number;
  tags?: string[];
  scenarioType?: 'ppt' | 'sales_analysis' | 'anomaly' | 'general';
  status?: 'running' | 'completed' | 'error' | 'idle' | 'hitl_pending';
}

export const MOCK_AGENT_SESSIONS: AgentChatSession[] = [
  {
    id: 'current',
    title: 'Q4 2025 경영 실적 보고서 분석',
    date: '2025-12-28',
    time: '14:30',
    messageCount: 8,
    tags: ['Report', 'Finance'],
    scenarioType: 'ppt',
    status: 'running',
  },
  {
    id: 's2',
    title: 'DID 사업부 원가 효율성 진단',
    date: '2025-12-27',
    time: '09:15',
    messageCount: 12,
    tags: ['DID', 'Cost Analysis'],
    scenarioType: 'sales_analysis',
    status: 'running',
  },
  {
    id: 's3',
    title: '일본 지사 환율 리스크 대응',
    date: '2025-12-26',
    time: '16:45',
    messageCount: 5,
    tags: ['Global', 'Risk'],
    scenarioType: 'general',
    status: 'hitl_pending',
  },
  {
    id: 's4',
    title: '신규 플랫폼 서비스 기획',
    date: '2025-12-20',
    time: '11:20',
    messageCount: 24,
    tags: ['Platform', 'Ideation'],
    scenarioType: 'general',
    status: 'completed',
  },
  {
    id: 's5',
    title: '12월 매출 실적 심층 분석',
    date: '2025-12-15',
    time: '10:00',
    messageCount: 6,
    tags: ['Finance', 'Analysis'],
    scenarioType: 'sales_analysis',
    status: 'completed',
  },
  {
    id: 's6',
    title: '메탈카드 고객사별 매출 트렌드',
    date: '2025-12-12',
    time: '15:40',
    messageCount: 18,
    tags: ['Metal Card', 'Trend'],
    scenarioType: 'sales_analysis',
  },
  {
    id: 's7',
    title: '2026년 사업 계획 초안 PPT',
    date: '2025-12-10',
    time: '09:00',
    messageCount: 32,
    tags: ['Report', 'Planning'],
    scenarioType: 'ppt',
  },
  {
    id: 's8',
    title: 'A은행 납품 단가 협상 자료',
    date: '2025-12-08',
    time: '13:20',
    messageCount: 10,
    tags: ['Client', 'Negotiation'],
    scenarioType: 'general',
  },
  {
    id: 's9',
    title: 'DID 칩 수급 이상 징후 탐지',
    date: '2025-12-05',
    time: '17:10',
    messageCount: 7,
    tags: ['DID', 'Anomaly'],
    scenarioType: 'anomaly',
  },
  {
    id: 's10',
    title: '11월 영업이익률 하락 원인 분석',
    date: '2025-12-03',
    time: '10:45',
    messageCount: 14,
    tags: ['Finance', 'Analysis'],
    scenarioType: 'sales_analysis',
  },
  {
    id: 's11',
    title: 'B카드사 계약 갱신 리스크 검토',
    date: '2025-11-28',
    time: '14:00',
    messageCount: 9,
    tags: ['Client', 'Risk'],
    scenarioType: 'general',
  },
  {
    id: 's12',
    title: 'Q3 실적 대비 Q4 예측 보고서',
    date: '2025-11-25',
    time: '11:30',
    messageCount: 22,
    tags: ['Report', 'Finance'],
    scenarioType: 'ppt',
  },
  {
    id: 's13',
    title: '해외 지사 통합 비용 시뮬레이션',
    date: '2025-11-20',
    time: '16:00',
    messageCount: 15,
    tags: ['Global', 'Cost Analysis'],
    scenarioType: 'general',
  },
  {
    id: 's14',
    title: '신규 거래처 C카드 온보딩 분석',
    date: '2025-11-15',
    time: '09:30',
    messageCount: 11,
    tags: ['Client', 'Onboarding'],
    scenarioType: 'sales_analysis',
  },
  {
    id: 's15',
    title: '원자재 가격 변동 영향 분석',
    date: '2025-11-10',
    time: '14:15',
    messageCount: 8,
    tags: ['Cost Analysis', 'Risk'],
    scenarioType: 'anomaly',
  },
  {
    id: 's16',
    title: '10월 사업부별 KPI 달성률 리뷰',
    date: '2025-11-05',
    time: '10:00',
    messageCount: 19,
    tags: ['KPI', 'Review'],
    scenarioType: 'sales_analysis',
  },
  {
    id: 's17',
    title: '메탈카드 수출 물량 예측 모델링',
    date: '2025-10-30',
    time: '15:20',
    messageCount: 27,
    tags: ['Metal Card', 'Forecast'],
    scenarioType: 'ppt',
    status: 'completed',
  },
  {
    id: 's18',
    title: 'D카드사 신규 계약 조건 분석',
    date: '2025-10-25',
    time: '09:45',
    messageCount: 13,
    tags: ['Client', 'Contract'],
    scenarioType: 'general',
  },
  {
    id: 's19',
    title: '3분기 재고 회전율 이상치 탐지',
    date: '2025-10-20',
    time: '14:30',
    messageCount: 6,
    tags: ['Inventory', 'Anomaly'],
    scenarioType: 'anomaly',
  },
  {
    id: 's20',
    title: '중국 지사 매출 급감 원인 분석',
    date: '2025-10-15',
    time: '11:00',
    messageCount: 21,
    tags: ['Global', 'Analysis'],
    scenarioType: 'sales_analysis',
  },
  {
    id: 's21',
    title: '연간 설비 투자 ROI 분석 보고서',
    date: '2025-10-10',
    time: '16:30',
    messageCount: 30,
    tags: ['Report', 'Investment'],
    scenarioType: 'ppt',
  },
  {
    id: 's22',
    title: '경쟁사 대비 원가 구조 비교',
    date: '2025-10-05',
    time: '13:15',
    messageCount: 16,
    tags: ['Cost Analysis', 'Competitor'],
    scenarioType: 'general',
  },
  {
    id: 's23',
    title: 'E은행 프리미엄카드 도입 제안서',
    date: '2025-09-28',
    time: '10:20',
    messageCount: 25,
    tags: ['Client', 'Proposal'],
    scenarioType: 'ppt',
  },
  {
    id: 's24',
    title: '9월 글로벌 매출 통합 리포트',
    date: '2025-09-25',
    time: '09:00',
    messageCount: 18,
    tags: ['Global', 'Report'],
    scenarioType: 'sales_analysis',
  },
  {
    id: 's25',
    title: 'DID 모듈 불량률 추이 모니터링',
    date: '2025-09-20',
    time: '15:45',
    messageCount: 9,
    tags: ['DID', 'Quality'],
    scenarioType: 'anomaly',
  },
];
