import React from 'react';
import { WidgetId, WidgetConfig } from '../types';
import {
  renderRevenueGrowthKPI,
  renderCostEfficiencyKPI,
  renderASPKPI,
  renderRevenueBridgeChart,
  renderCostCorrelationChart,
  renderAnomalyCostChart,
} from '../components/widgets';

// Liveboard Widget Registry
export const WIDGET_REGISTRY: Record<WidgetId, WidgetConfig> = {
  'revenue_growth_kpi': {
    id: 'revenue_growth_kpi',
    title: '매출 성장률',
    minW: 2,
    minH: 2,
    defaultW: 4,
    defaultH: 3,
    render: renderRevenueGrowthKPI,
  },
  'cost_efficiency_kpi': {
    id: 'cost_efficiency_kpi',
    title: '원가 효율성',
    minW: 2,
    minH: 2,
    defaultW: 4,
    defaultH: 3,
    render: renderCostEfficiencyKPI,
  },
  'asp_kpi': {
    id: 'asp_kpi',
    title: '평균 판매 단가',
    minW: 2,
    minH: 2,
    defaultW: 4,
    defaultH: 3,
    render: renderASPKPI,
  },
  'revenue_bridge_chart': {
    id: 'revenue_bridge_chart',
    title: '매출 증감 요인 분석',
    minW: 4,
    minH: 4,
    defaultW: 6,
    defaultH: 8,
    render: renderRevenueBridgeChart,
  },
  'cost_correlation_chart': {
    id: 'cost_correlation_chart',
    title: '자동화율과 원가율 상관관계',
    minW: 4,
    minH: 4,
    defaultW: 6,
    defaultH: 8,
    render: renderCostCorrelationChart,
  },
  'anomaly_cost_chart': {
    id: 'anomaly_cost_chart',
    title: '시간대별 원가율 추이',
    minW: 4,
    minH: 4,
    defaultW: 6,
    defaultH: 8,
    render: renderAnomalyCostChart,
  },
  // Placeholder widgets for future expansion
  'monthly_trend_chart': {
    id: 'monthly_trend_chart',
    title: '월별 매출 추이',
    minW: 4,
    minH: 4,
    defaultW: 12,
    defaultH: 8,
    render: () => React.createElement('div', null, 'Chart Placeholder'),
  },
  'business_composition_chart': {
    id: 'business_composition_chart',
    title: '사업부별 매출 구성',
    minW: 4,
    minH: 4,
    defaultW: 6,
    defaultH: 8,
    render: () => React.createElement('div', null, 'Chart Placeholder'),
  },
  'top_clients_chart': {
    id: 'top_clients_chart',
    title: '주요 거래처 Top 5',
    minW: 4,
    minH: 4,
    defaultW: 6,
    defaultH: 8,
    render: () => React.createElement('div', null, 'Chart Placeholder'),
  },
  'yoy_growth_chart': {
    id: 'yoy_growth_chart',
    title: 'YoY 성장률',
    minW: 4,
    minH: 4,
    defaultW: 6,
    defaultH: 8,
    render: () => React.createElement('div', null, 'Chart Placeholder'),
  },
};
